### ISSUE TITLE
橡皮擦能否只擦掉显示的图层 ， 不要影响隐藏的图层

### ISSUE THREAD

**Issue by hxzAugustinus** [LHRUN/paint-board#10]

**Comment by LHRUN** [comment]
橡皮擦在我最初设计的时候没有考虑这么多，但随着功能的增加有些难以处理，在最近忙完工作之后准备出一个版本做这些细节的调整以及布局的调整，为之后的画笔DIY配置做铺垫
橡皮擦影响隐藏的图层这个问题，我建议把隐藏的图层排序在橡皮擦图层之上，就不会影响
