### ISSUE TITLE
撤销操作，如果快速撤销至清空，再快速的画一笔，再次撤销时最后一笔无法撤销

### ISSUE THREAD

**Issue by llwpll** [LHRUN/paint-board#11]
![image](https://github.com/LHRUN/paint-board/assets/74346350/9dda6dc1-adca-47f8-b7c6-770e9d32fd87)
快速撤销操作时将cacheStack的第一个空list删除了，后续操作过程中操作会有异常

**Comment by LHRUN** [comment]
@llwpll 多谢提出，已在0.2.4修复
