### ISSUE TITLE
”多色“ 期望增加下面的效果

### ISSUE THREAD

**Issue by donghaobo** [LHRUN/paint-board#23]
<img width="417" alt="KIM20240108-327046" src="https://github.com/LHRUN/paint-board/assets/9133585/74f1cd64-14d9-4327-af08-119d4fbd5055">
上面是实际画出来的效果，希望是下面那条线的效果

**Comment by LHRUN** [comment]
抱歉，这个短期内不太会支持，暂时不会制定这个画笔的调整计划，记录了，不过感谢你的关注和建议
