### ISSUE TITLE
希望可以平移视角(类似无边界)跟直线连接功能

### ISSUE THREAD

**Issue by 1026742642** [LHRUN/paint-board#24]
希望可以平移视角(类似无边界)跟直线连接功能

**Comment by LHRUN** [comment]
平移是支持的。PC端按住空格，点击鼠标移动即可。移动端是双指同时按压然后移动。

直线连接是什么意思

@1026742642

**Comment by 1026742642** [comment]
就是画两个点之间的直线

**Comment by LHRUN** [comment]
这个会支持的，按照计划应该是年后，会完成一些常用图形的效果绘制，多谢建议 @1026742642

**Comment by LHRUN** [comment]
常用形状以及直线绘制 1.3.0 版本已支持
