### ISSUE TITLE
撤回与反撤回

### ISSUE THREAD

**Issue by Tomaolala** [LHRUN/paint-board#3]
是如何记录对自由曲线的操作呢，实现撤回与反撤回，我用的putImgdata会覆盖之前的内容 @LHRUN

**Comment by LHRUN** [comment]
建议不要通过ImageData这种形式记录，数据太大，我是记录了移动的所有坐标，然后画布的每次改变都是清除画布后再遍历所有画布元素重新绘画。实现撤回和反撤回，我是记录了一个变量step，用于限制遍历画布元素数组，比如我现在canvas上有三个元素，点击撤回，就step-1，把变量记录到第二个元素，点击反撤回，就step+1，具体代码可看(https://github.com/LHRUN/paint-board/blob/main/src/utils/history.ts)   @Tomaolala

**Comment by Tomaolala** [comment]
> 建议不要通过ImageData这种形式记录，数据太大，我是记录了移动的所有坐标，然后画布的每次改变都是清除画布后再遍历所有画布元素重新绘画。实现撤回和反撤回，我是记录了一个变量step，用于限制遍历画布元素数组，比如我现在canvas上有三个元素，点击撤回，就step-1，把变量记录到第二个元素，点击反撤回，就step+1，具体代码可看(https://github.com/LHRUN/paint-board/blob/main/src/utils/history.ts) @Tomaolala

但是储存的点不会太多的嘛

**Comment by Tomaolala** [comment]
> 多，这是我目前知道最好的方案，基本上现在的画图平台都是这样实现的，比如[excalidraw](https://excalidraw.com/) @Tomaolala

好的，感谢:beers:
