### ISSUE TITLE
非常`nice`的项目，希望能对一些操作按钮添加`Tooltip`提示

### ISSUE THREAD

**Issue by xiaoxian521** [LHRUN/paint-board#30]
### 问题描述 (Description of the problem)

如下：

<img width="1255" alt="image" src="https://github.com/LHRUN/paint-board/assets/44761321/f845b5bc-9fab-482b-8009-0aff05f25e8a">

### 如何复现该问题 (How to reproduce the problem)

none

### 操作系统和浏览器信息 (Operating System and Browser Information)

mac google

**Comment by LHRUN** [comment]
@xiaoxian521 已修复，这个之前是有的，在做移动端兼容时改没了 😂
