### ISSUE TITLE
项目打包为tauri软件后，在1080p显示器上字体严重模糊

### ISSUE THREAD

**Issue by ccc0818** [LHRUN/paint-board#36]
### 问题描述 (Description of the problem)

![Snipaste](https://github.com/LHRUN/paint-board/assets/56196628/28174955-8d11-4c97-816a-05966b6ad650)

### 如何复现该问题 (How to reproduce the problem)

打包为tauri app

### 操作系统和浏览器信息 (Operating System and Browser Information)

macos14

**Comment by LHRUN** [comment]
tauri 我没有试过, 不过之前有人反馈过 windows 系统某些浏览器低版本也会出现字体模糊, 应该是一个问题, 等我后面找一个 windows 环境运行一下进行修复 @ccc0818

**Comment by LHRUN** [comment]
1.3.1 版本已更新中文字体, 我在跨浏览器测试平台模拟环境已显示正常 @ccc0818
