### ISSUE TITLE
在chrome36上打不开，一片空白

### ISSUE THREAD

**Issue by Mengdch** [LHRUN/paint-board#37]
### 问题描述 (Description of the problem)

使用com.android.chrome-36.0.1985.135-1985135打开网页一片空白

### 如何复现该问题 (How to reproduce the problem)

安装chrome36版本，打开https://songlh.top/paint-board/

### 操作系统和浏览器信息 (Operating System and Browser Information)

andorid5.0.1
chrome36.0.1985.135

**Comment by LHRUN** [comment]
这个版本太低了, 某些 API 已经不提供支持了, 后面我会更新一个兼容版本, 看能兼容到最低版本是多少, 同时会注明到 README 中

**Comment by Mengdch** [comment]
好的，非常期待
