### ISSUE TITLE
是否支持仅擦除图片上的笔迹标注

### ISSUE THREAD

**Issue by betsylotus** [LHRUN/paint-board#48]
### 问题描述 (Description of the problem)

![QQ20241120-133648](https://github.com/user-attachments/assets/a514fac2-ae46-4d56-bc10-6d1cc4498e08)

canvas中上传图片，在图片上做些标注，但是利用板擦擦除的时候，会同事擦除图片的内容。能否支持板擦仅擦除图片上的笔迹标注内容

### 如何复现该问题 (How to reproduce the problem)

![QQ20241120-133648](https://github.com/user-attachments/assets/0ff6c57d-0151-475b-997f-75a7c34950a5)

### 操作系统和浏览器信息 (Operating System and Browser Information)

Microsoft Windows [版本 10.0.22631.4460]

**Comment by LHRUN** [comment]
好建议, 已经支持了, 在最新版你可以 选择 Tab 下进行配置 @betsylotus 
<img width="317" alt="" src="https://github.com/user-attachments/assets/a9c813ef-37d7-4d93-85b9-12fa6b8fc56f">
