### ISSUE TITLE
资源加载问题

### ISSUE THREAD

**Issue by itelite** [LHRUN/paint-board#51]
### 问题描述 (Description of the problem)

![image](https://github.com/user-attachments/assets/b47a6092-7ace-4d36-94ad-66fdef145613)
项目需要加载的资源，比如图片、字体之类的，能不能考虑直接存放在项目里，不用再去请求其他站点，这样更有利于本地部署访问，避免因为网络问题造成体验不好

### 如何复现该问题 (How to reproduce the problem)

无

### 操作系统和浏览器信息 (Operating System and Browser Information)

docker运行1.5.4版本

**Comment by itelite** [comment]
![Snipaste_2024-11-30_11-22-59](https://github.com/user-attachments/assets/92b00a91-97e5-4ba9-a958-6b558f863a30)

**Comment by LHRUN** [comment]
@itelite 图片我后面可以放到项目里，但是字体我不会放，不太好处理（假如有更新的话），字体你可以自己下载放到项目中，都是 google 的
